services:
  web:
    build: ./store
    image: web:1.0.0
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    develop:
      watch:
        - action: sync
          path: ./store
          target: /usr/src/store
          ignore:
            - node_modules/
            - venv/
        - action: rebuild
          path: ./store/requirements.txt
        - action: rebuild
          path: ./store/entrypoint.sh
    restart: unless-stopped #no, always, on-failure: 5, unless-stopped
    env_file:
      - ./store/.env.dev
    depends_on:
      - db
  db:
    image: postgres:16-bookworm
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped #no, always, on-failure: 5, unless-stopped
    environment:
      - POSTGRES_USER=textura
      - POSTGRES_PASSWORD=textura
      - POSTGRES_DB=textura
  dbbrowser:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  data: